language: python
python:
  - 3.9
before_install:
  - sudo apt-get -y install
install:
  pip install -r requirements-dev.txt codecov
script:
  - flake8
  - pytest examplepython --cov=examplepython
after_success:
  - codecov