language: python
python:
  - 3.9
before_install:
  - sudo apt-get -y install
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
script:
  - flake8
  - pytest examplepython --cov=examplepython
after_success:
  - codecov